---
version: '3'

volumes:
  volume_pihole_dnsmasq:
  volume_pihole_general:
    external: true

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSMASQ_LISTENING: local # default
      DNS_FQDN_REQUIRED: "false" # Enabling CF will forward all hostnames (non-FQDNs) to router when "Never forward non-FQDNs" is NOT enabled
      DNS_BOGUS_PRIV: "true" # default
      DNSSEC: "true"
      REV_SERVER: "true"
      REV_SERVER_CIDR: "${REV_SERVER_CIDR}"
      REV_SERVER_TARGET: "${REV_SERVER_TARGET}"
      FTLCONF_LOCAL_IPV4: "${FTLCONF_LOCAL_IPV4}"
      WEBTHEME: default-darker
    volumes:
      - volume_pihole_dnsmasq:/etc/dnsmasq.d/
      - volume_pihole_general:/etc/pihole/
