---
name: pihole

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:development
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: "${DEVICE_TIMEZONE}"

      FTLCONF_dns_upstreams: "127.0.0.1#5335"
      FTLCONF_dns_listeningMode: "local"
      FTLCONF_dns_domainNeeded: true
      FTLCONF_dns_bogusPriv: true
      FTLCONF_dns_dnssec: true
      FTLCONF_dns_revServers: "true,${NETWORK_CIDR},${NETWORK_GATEWAY},${NETWORK_DOMAIN}"
      FTLCONF_dns_piholePTR: "HOSTNAMEFQDN"

      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_webserver_api_maxClients: 20
      FTLCONF_webserver_interface_theme: "default-darker"

      FTLCONF_dns_domain: "${NETWORK_DOMAIN}"
      FTLCONF_webserver_domain: "${NETWORK_DOMAIN}"
    volumes:
      - volume_pihole:/etc/pihole/

volumes:
  volume_pihole:
    external: true
