---
name: pihole

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:development
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: "${DEVICE_TIMEZONE}"
      FTLCONF_dns_upstreams: "127.0.0.1#5335"
      FTLCONF_dns_piholePTR: "NONE" # "HOSTNAMEFQDN"
      FTLCONF_dns_domainNeeded: true
      FTLCONF_dns_domain: "${NETWORK_DOMAIN}" # test
      FTLCONF_dns_dnssec: true
      FTLCONF_dns_revServers: "true,${NETWORK_CIDR},${NETWORK_GATEWAY},${NETWORK_DOMAIN}"
      FTLCONF_dns_cache_optimizer: -1
      FTLCONF_webserver_domain: "${NETWORK_DOMAIN}" # test
      FTLCONF_webserver_interface_theme: "default-darker"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_webserver_api_maxClients: 20
    volumes:
      - volume_pihole:/etc/pihole/

volumes:
  volume_pihole:
    external: true
