---
name: pihole

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: "${DEVICE_TIMEZONE}"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSMASQ_LISTENING: local
      DNS_FQDN_REQUIRED: "true"
      DNS_BOGUS_PRIV: "true"
      DNSSEC: "true"
      REV_SERVER: "true"
      REV_SERVER_CIDR: "${REV_SERVER_CIDR}"
      REV_SERVER_TARGET: "${REV_SERVER_TARGET}"
#      REV_SERVER_DOMAIN: "${REV_SERVER_DOMAIN}"
      FTLCONF_LOCAL_IPV4: "${FTLCONF_LOCAL_IPV4}"
      WEBTHEME: default-darker
    volumes:
      - volume_pihole_dnsmasq:/etc/dnsmasq.d/
      - volume_pihole_general:/etc/pihole/

volumes:
  volume_pihole_dnsmasq:
  volume_pihole_general:
    external: true
