---
name: unbound

services:
  unbound:
    container_name: unbound
    hostname: unbound
    image: "${UNBOUND_IMAGE}"
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: "${DEVICE_TIMEZONE}"
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    healthcheck:
      disable: true
