---
- name: 'HOSTNAME : disable cloud-init updating hostname'
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    search_string: '{{ item.search_string }}'
    line: '{{ item.line }}'
  loop:
    - { search_string: 'preserve_hostname: false', line: 'preserve_hostname: true' }
    - { search_string: '- update_etc_hosts', line: '#- update_etc_hosts' }
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: 'HOSTNAME : change name in /etc/hosts'
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1(\s*)'
    line: '127.0.1.1\1{{ device_hostname }}'
    backrefs: true
  become: true

- name: 'HOSTNAME : change hostname'
  ansible.builtin.hostname:
    name: '{{ device_hostname }}'
  become: true
