---
- block:
    - name: 'STUB : disable stub in config'
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '#?DNSStubListener=yes'
        line: 'DNSStubListener=no'
        backrefs: true
      register: stub_resolver

    - block:
        - name: 'STUB : remove current resolver'
          ansible.builtin.file:
            path: /etc/resolv.conf
            state: absent

        - name: 'STUB : create new resolver with sym link'
          ansible.builtin.file:
            src: /run/systemd/resolve/resolv.conf
            dest: /etc/resolv.conf
            state: link

        - name: 'STUB : restart service'
          ansible.builtin.service:
            name: systemd-resolved
            state: restarted
      when: stub_resolver.changed
  become: true
  when: ansible_distribution == 'Ubuntu'
