---
- name: 'STUB : disable stub resolver'
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    search_string: '#DNSStubListener=yes'
    line: 'DNSStubListener=no'
  become: true
  register: out

- name: 'STUB : remove current file'
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true
  when: out.changed

- name: 'STUB : create new symbolic link'
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: true
  when: out.changed

- name: 'STUB : restart systemd-resolved service'
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  become: true
  when: out.changed
