---
- name: 'NETPLAN : copy template'
  ansible.builtin.template:
    src: templates/99-netplan_dhcp.yaml.j2
    dest: /etc/netplan/99-netplan_dhcp.yaml
    mode: '0644'
  become: true
  register: netplan

- name: 'NETPLAN : apply plan'
  ansible.builtin.command:
    cmd: netplan apply
  become: true
  when: netplan.changed
