---
- name: 'NETPLAN : copy static_ip template'
  ansible.builtin.template:
    src: templates/netplan_static_ip.yaml.j2
    dest: /etc/netplan/static_ip.yaml
    mode: '0644'
  become: true
  register: out

- name: 'NETPLAN : apply plan'
  ansible.builtin.command:
    cmd: netplan apply
  become: true
  when: out.changed
