---
- name: 'CLOUD-INIT : check if service is running'
  ansible.builtin.service:
    name: cloud-init.service
  register: service_info

- name: 'CLOUD-INIT : disable service'
  ansible.builtin.file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve
  become: true
  when: service_info.status.ActiveState == 'active'

#- name: 'CLOUD-INIT : disable cloud-init updating hostname'
#  ansible.builtin.lineinfile:
#    path: /etc/cloud/cloud.cfg
#    search_string: '{{ item.search_string }}'
#    line: '{{ item.line }}'
#  loop:
#    - { search_string: 'preserve_hostname: false', line: 'preserve_hostname: true' }
#    - { search_string: '- update_etc_hosts', line: '#- update_etc_hosts' }
#  become: true
#  when: service_info.status.ActiveState == 'active'
