---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    device_hostname: Raspberry-Pi-4B   # used in: GITHUB.HOSTNAME.ROLE
    device_timezone: Europe/Amsterdam  # used in: GITHUB.TIMEZONE.ROLE

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - GITHUB.UPDATE.ROLE
    - GITHUB.CLOUD_INIT.ROLE
    - GITHUB.HOSTNAME.ROLE
    - GITHUB.TIMEZONE.ROLE

  tasks:
    - import_tasks: tasks/1_stub-resolver.yml
    - import_tasks: tasks/2_docker.yml
