---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    device_hostname: Raspberry-Pi-5    # used in: GITHUB.HOSTNAME.ROLE
    device_timezone: Europe/Amsterdam  # used in: GITHUB.TIMEZONE.ROLE - templates/.env.j2
    pihole_password: finch             # used in: templates/.env.j2

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - role: GITHUB.UPDATE.ROLE
    - role: GITHUB.HOSTNAME.ROLE
    - role: GITHUB.TIMEZONE.ROLE

  tasks:
    - import_tasks: tasks/1_stub-resolver.yml # used for pi-hole on ubuntu
    - import_tasks: tasks/2_docker.yml
