---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    device_hostname: Raspberry-Pi-4B   # used in: tasks/1_hostname.yml
    device_timezone: Europe/Amsterdam  # used in: tasks/2_timezone.yml

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - GITHUB.UPDATE.ROLE

  tasks:
    - import_tasks: tasks/1_hostname.yml
    - import_tasks: tasks/2_timezone.yml
    - import_tasks: tasks/3_docker.yml
