---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    network_cidr: /24                 # used in: netplan_static_ip.yaml.j2 .env.j2
    gateway_ip: 192.168.178.1         # used in: netplan_static_ip.yaml.j2 .env.j2
    device_ip: 192.168.178.4          # used in: netplan_static_ip.yaml.j2 .env.j2
    device_hostname: Raspberry-Pi-4B  # used in: 1_hostname.yml
    device_interface: eth0            # used in: netplan_static_ip.yaml.j2

  pre_tasks:
    - name: 'Connect to host & retrieve min facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'

  roles:
    - GITHUB.UPDATE.ROLE

  tasks:
    - import_tasks: tasks/1_hostname.yml
    - import_tasks: tasks/2_timezone.yml
    - import_tasks: tasks/3_docker.yml
    - import_tasks: tasks/4_netplan.yml
